general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.98
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15

[cursor]
style = { shape = "Underline" }
unfocused_hollow = false
